<?php
$typeArr[1] = '关于工作室';
$typeArr[2] = '新页面';
$typeArr[3] = '经典案例';
$typeArr[4] = '专业组织';
$typeArr[5] = '合作伙伴';
$typeArr[6] = '荣誉墙';
$typeArr[24] = '关于文俊';
$typeArr[25] = '视频资料';
$typeArr[8] = '解决方案';
$typeArr[9] = '工作室环境';
$typeArr[10] = '智能建筑';
$typeArr[11] = '新页面';
$typeArr[12] = '智能游艇';
$typeArr[13] = '产品系列';
$typeArr[14] = 'Buspro';
$typeArr[15] = 'KNX';
$typeArr[16] = '无线产品';
$typeArr[17] = '技术支持';
$typeArr[18] = '技术培训';
$typeArr[19] = '常见问题';
$typeArr[20] = '经典案例';
$typeArr[21] = '联系我们';
$typeArr[22] = '联系我们';
$typeArr[23] = '社交媒体';
$typeArr[26] = '实景案例';
?>