<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/151012/1-151012144444.jpg ",93,240);
$z[1][4]['ddimg']="/uploads/allimg/151012/1-151012144444.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="500";
$z[1][4]['height']="500";
$z[2]=Array("img"," /uploads/allimg/151012/1-151012144444-50.jpg ",242,395);
$z[2][4]['ddimg']="/uploads/allimg/151012/1-151012144444-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="500";
$z[2][4]['height']="500";
$z[3]=Array("img"," /uploads/allimg/151012/1-151012144445.jpg ",397,544);
$z[3][4]['ddimg']="/uploads/allimg/151012/1-151012144445.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="500";
$z[3][4]['height']="500";

?>