<a href="[field:arcurl/]">
    <div class="child" id="work[field:global name=autoindex runphp="yes"]@me=@me+1;[/field:global]"> <img class="childImg" src="[field:picname/]" />
      <p class="childTitle">[field:title/]</p>
      <img class="childFoot" src="/skin/images/projectfixed.png" /> <img class="childRight" src="/skin/images/projecticon.png" />
      <div class="childHide"></div>
      <img class="childSearch" src="/skin/images/projectsearch.png" />
      <div class="childSearchBg"></div>
    </div>
    </a>