<?php
$z[0]=Array("field","",264,283);
$z[0][4]['name']="title";
$z[1]=Array("global","",284,310);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",351,373);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",413,464);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",651,686);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",976,1005);
$z[5][4]['name']="position";
$z[6]=Array("productimagelist","<img src=\"[field:imgsrc/]\" />",1241,1317);
$z[7]=Array("productimagelist","\r\n          <div class=\"child\"><img src=\"[field:imgsrc/]\" /></div>\r\n          ",1373,1498);
$z[8]=Array("field","",1754,1773);
$z[8][4]['name']="title";
$z[9]=Array("field","",1836,1861);
$z[9][4]['name']="description";
$z[10]=Array("field","",1899,1915);
$z[10][4]['name']="xh";
$z[11]=Array("field","",1953,1969);
$z[11][4]['name']="lb";
$z[12]=Array("field","",2334,2352);
$z[12][4]['name']="body";
$z[13]=Array("field","",2402,2418);
$z[13][4]['name']="gn";
$z[14]=Array("field","",2455,2471);
$z[14][4]['name']="cs";
$z[15]=Array("arclist"," <a href=\"[field:arcurl/]\">\r\n        <div class=\"child\">\r\n          <div class=\"childImg\"><img src=\"[field:picname/]\" /></div>\r\n          <div class=\"childTitle\">\r\n            <p>[field:title/]</p>\r\n          </div>\r\n          <div class=\"childSub\"></div>\r\n          <div class=\"childInfo\"> <img src=\"/skin/images/listicon.jpg\" /> <span>详细信息</span> </div>\r\n        </div>\r\n        </a> ",4093,4534);
$z[15][4]['typeid']="13";
$z[15][4]['row']="4";
$z[16]=Array("include","",4638,4675);
$z[16][4]['filename']="footer.htm";

?>