<div class="child">
        <div class="childImg"> <img class="childImgimg" src="[field:picname/]" />
          <div class="childHide"> <a class="example-image-link" href="[field:picname/]" data-lightbox="child1"> </a> <a href="[field:arcurl/]">
            <div class="childHideIcon"><img src="/skin/images/linkicon.png" /></div>
            </a> </div>
        </div>
        <a href="[field:arcurl/]">
        <p class="childTitle">[field:title/]</p>
        </a>
        <p class="childTime">[field:pubdate function="MyDate('Y-m-d',@me)"/]</p>
        <a href="[field:arcurl/]">
        <p class="childInfo">[field:description/]...</p>
        </a> <a class="example-image-link" href="[field:picname/]" data-lightbox="child1" ></a> </div>