<?php
$z[0]=Array("channelartlist","\r\n    <li class=\"child {dede:field.currentstyle/}\"> <a href=\"{dede:field name='typeurl'/}\">\r\n      <p class=\"title\">{dede:field name='typename'/}</p>\r\n      </a>\r\n      <ul class=\"childContent\">\r\n        {dede:channel type='son' noself='yes'} <a href=\"[field:typeurl/]\">\r\n        <li class=\"childContentLi\">[field:typename/]</li>\r\n        </a> {/dede:channel}\r\n      </ul>\r\n      <img class=\"wapNavPointer\" src=\"/skin/images/wapnavpointer.jpg\" /> </li>\r\n    ",1752,2284);
$z[0][4]['typeid']="top";
$z[0][4]['currentstyle']="on";
$z[1]=Array("global","",2563,2588);
$z[1][4]['name']="cfg_cmsurl";

?>