<?php
$z[0]=Array("field","",288,307);
$z[0][4]['name']="title";
$z[1]=Array("global","",308,334);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",379,408);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",452,510);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",713,748);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",997,1026);
$z[5][4]['name']="typename";
$z[6]=Array("field","",1057,1086);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n          <div class=\"child leftChild\" id=\"case11\">\r\n        <div class=\"childImg\"><img src=\"[field:picname/]\" /></div>\r\n        <div class=\"childInfo\"> <a href=\"[field:arcurl/]\">\r\n          <p class=\"childTitle2\">[field:title/]</p>\r\n          </a>\r\n              <div class=\"childInfo2\">[field:description/]...</div>\r\n            </div>\r\n      </div>\r\n          ",1593,1995);
$z[7][4]['pagesize']="10";
$z[8]=Array("include","",2159,2196);
$z[8][4]['filename']="footer.htm";

?>