<?php
$z[0]=Array("field","",264,283);
$z[0][4]['name']="title";
$z[1]=Array("global","",284,310);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",351,380);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",420,478);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",665,700);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",968,997);
$z[5][4]['name']="position";
$z[6]=Array("list"," <a href=\"[field:arcurl/]\">\r\n      <div class=\"child\">\r\n        <div class=\"childImg\"><img src=\"[field:picname/]\" /></div>\r\n        <div class=\"childTitle\">\r\n          <p>[field:title/]</p>\r\n        </div>\r\n        <div class=\"childSub\"></div>\r\n        <div class=\"childInfo\"> <img src=\"/skin/images/listicon.jpg\" /> <span>详细信息</span> </div>\r\n      </div>\r\n      </a> ",1116,1529);
$z[6][4]['pagesize']="24";
$z[7]=Array("include","",1595,1632);
$z[7][4]['filename']="footer.htm";

?>