<?php
$z[0]=Array("field","",264,283);
$z[0][4]['name']="title";
$z[1]=Array("global","",284,310);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",351,380);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",420,478);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",665,700);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",993,1022);
$z[5][4]['name']="typename";
$z[6]=Array("field","",1053,1082);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n      <div class=\"child\">\r\n        <div class=\"childImg\"> <img class=\"childImgimg\" src=\"[field:picname/]\" />\r\n          <div class=\"childHide\"> <a class=\"example-image-link\" href=\"[field:picname/]\" data-lightbox=\"child1\"> </a> <a href=\"[field:arcurl/]\">\r\n            <div class=\"childHideIcon\"><img src=\"/skin/images/linkicon.png\" /></div>\r\n            </a> </div>\r\n        </div>\r\n        <a href=\"[field:arcurl/]\">\r\n        <p class=\"childTitle\">[field:title/]</p>\r\n        </a>\r\n        <p class=\"childTime\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</p>\r\n        <a href=\"[field:arcurl/]\">\r\n        <p class=\"childInfo\">[field:description/]...</p>\r\n        </a> <a class=\"example-image-link\" href=\"[field:picname/]\" data-lightbox=\"child1\" ></a> </div>\r\n      ",1512,2319);
$z[7][4]['pagesize']="12";
$z[8]=Array("pagelist","",2347,2413);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2491,2528);
$z[9][4]['filename']="footer.htm";

?>