<?php
$z[0]=Array("global","",274,300);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",341,370);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",410,468);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",655,690);
$z[3][4]['filename']="head.htm";
$z[4]=Array("list"," <a href=\"[field:arcurl/]\">\r\n      <div class=\"child\">\r\n        <div class=\"childImg\"><img src=\"[field:picname/]\"></div>\r\n        <div class=\"childTitle\">\r\n          <p>[field:title/]</p>\r\n        </div>\r\n        <div class=\"childSub\"></div>\r\n        <div class=\"childInfo\"> <img src=\"/skin/images/listIcon.jpg\"> <span>详细信息</span> </div>\r\n      </div>\r\n      </a> ",1284,1692);
$z[4][4]['perpage']="30";
$z[5]=Array("include","",1758,1795);
$z[5][4]['filename']="footer.htm";

?>